/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Diet App
 * API para o Diet App
 * OpenAPI spec version: 0.0.1
 */
import { customFetch } from '../../fetchMutator'
export type PostGenPlanBodyActivityLevel =
  (typeof PostGenPlanBodyActivityLevel)[keyof typeof PostGenPlanBodyActivityLevel]

export const PostGenPlanBodyActivityLevel = {
  sedentario: 'sedentario',
  '2x_semana': '2x_semana',
  '4x_semana': '4x_semana',
} as const

export type PostGenPlanBodyGenre =
  (typeof PostGenPlanBodyGenre)[keyof typeof PostGenPlanBodyGenre]

export const PostGenPlanBodyGenre = {
  masculino: 'masculino',
  feminino: 'feminino',
  outro: 'outro',
} as const

export type PostGenPlanBodyGoal =
  (typeof PostGenPlanBodyGoal)[keyof typeof PostGenPlanBodyGoal]

export const PostGenPlanBodyGoal = {
  perda_de_peso: 'perda_de_peso',
  hipertrofia: 'hipertrofia',
  manter_massa_muscular: 'manter_massa_muscular',
} as const

export type PostGenPlanBody = {
  /** @minLength 2 */
  name: string
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  weight: number
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  height: number
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum
   */
  age: number
  activityLevel: PostGenPlanBodyActivityLevel
  genre: PostGenPlanBodyGenre
  goal: PostGenPlanBodyGoal
}

export type PostGenPlan400 = {
  error: string
  details: unknown
}

export type PostAuthBody = {
  /** @minLength 2 */
  name?: string
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string
  /** @minLength 6 */
  password: string
}

export type PostAuth200 = {
  token: string
}

export type PostAuth400 = {
  message: string
}

export type PostAuth401 = {
  message: string
}

export type PostAuth404 = {
  message: string
}

export type PatchUserBodyActivityLevel =
  (typeof PatchUserBodyActivityLevel)[keyof typeof PatchUserBodyActivityLevel]

export const PatchUserBodyActivityLevel = {
  sedentario: 'sedentario',
  '2x_semana': '2x_semana',
  '4x_semana': '4x_semana',
} as const

export type PatchUserBodyGenre =
  (typeof PatchUserBodyGenre)[keyof typeof PatchUserBodyGenre]

export const PatchUserBodyGenre = {
  masculino: 'masculino',
  feminino: 'feminino',
  outro: 'outro',
} as const

export type PatchUserBodyGoal =
  (typeof PatchUserBodyGoal)[keyof typeof PatchUserBodyGoal]

export const PatchUserBodyGoal = {
  perda_de_peso: 'perda_de_peso',
  hipertrofia: 'hipertrofia',
  manter_massa_muscular: 'manter_massa_muscular',
} as const

export type PatchUserBody = {
  /** @minLength 2 */
  name?: string
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  weight?: number
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  height?: number
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum
   */
  age?: number
  activityLevel?: PatchUserBodyActivityLevel
  genre?: PatchUserBodyGenre
  goal?: PatchUserBodyGoal
}

export type PatchUser200 = {
  message: string
}

export type PatchUser400 = {
  message: string
}

export type PatchUser401 = {
  message: string
}

/**
 * @nullable
 */
export type GetUser200ActivityLevel =
  | (typeof GetUser200ActivityLevel)[keyof typeof GetUser200ActivityLevel]
  | null

export const GetUser200ActivityLevel = {
  sedentario: 'sedentario',
  '2x_semana': '2x_semana',
  '4x_semana': '4x_semana',
} as const

/**
 * @nullable
 */
export type GetUser200Genre =
  | (typeof GetUser200Genre)[keyof typeof GetUser200Genre]
  | null

export const GetUser200Genre = {
  masculino: 'masculino',
  feminino: 'feminino',
  outro: 'outro',
} as const

/**
 * @nullable
 */
export type GetUser200Goal =
  | (typeof GetUser200Goal)[keyof typeof GetUser200Goal]
  | null

export const GetUser200Goal = {
  perda_de_peso: 'perda_de_peso',
  hipertrofia: 'hipertrofia',
  manter_massa_muscular: 'manter_massa_muscular',
} as const

/**
 * @nullable
 */
export type GetUser200Plan = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string
  content: string
  /** @nullable */
  createdAt: string | null
} | null

export type GetUser200 = {
  name: string
  /** @nullable */
  weight?: number | null
  /** @nullable */
  height?: number | null
  /** @nullable */
  age?: number | null
  /** @nullable */
  activityLevel?: GetUser200ActivityLevel
  /** @nullable */
  genre?: GetUser200Genre
  /** @nullable */
  goal?: GetUser200Goal
  /** @nullable */
  plan?: GetUser200Plan
}

export type GetUser401 = {
  message: string
}

export type GetUser404 = {
  message: string
}

export type GetUser500 = {
  message: string
}

export type PostPostPlanBody = {
  content: string
}

export type PostPostPlan200 = {
  success: boolean
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  planId: string
}

export type PostPostPlan400 = {
  error: string
  details: unknown
}

export type GetGetPlan200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string
  content: string
  /** @nullable */
  createdAt: string | null
}

export type GetGetPlan400 = {
  error: string
  details: unknown
}

export type DeleteDeletePlan200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  planId: string
}

export type DeleteDeletePlan400 = {
  error: string
  details: unknown
}

export const getGetUrl = () => {
  return `http://localhost:3333/`
}

export const get = async (options?: RequestInit): Promise<void> => {
  return customFetch<void>(getGetUrl(), {
    ...options,
    method: 'GET',
  })
}

/**
 * Recebe os dados do usuário e retorna o plano alimentar em streaming (SSE).
 * @summary Gera um plano alimentar personalizado
 */
export const getPostGenPlanUrl = () => {
  return `http://localhost:3333/genPlan`
}

export const postGenPlan = async (
  postGenPlanBody: PostGenPlanBody,
  options?: RequestInit,
): Promise<string> => {
  return customFetch<string>(getPostGenPlanUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postGenPlanBody),
  })
}

/**
 * Se o usuário não existir, uma nova conta será criada. Se o usuário já existir, ele será autenticado.
 * @summary Cria uma nova conta ou autentica um usuário existente
 */
export const getPostAuthUrl = () => {
  return `http://localhost:3333/auth`
}

export const postAuth = async (
  postAuthBody: PostAuthBody,
  options?: RequestInit,
): Promise<PostAuth200> => {
  return customFetch<PostAuth200>(getPostAuthUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postAuthBody),
  })
}

/**
 * Permite ao usuário autenticado atualizar seus próprios dados. Todos os campos são opcionais.
 * @summary Atualiza os dados do usuário autenticado
 */
export const getPatchUserUrl = () => {
  return `http://localhost:3333/user`
}

export const patchUser = async (
  patchUserBody: PatchUserBody,
  options?: RequestInit,
): Promise<PatchUser200> => {
  return customFetch<PatchUser200>(getPatchUserUrl(), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchUserBody),
  })
}

/**
 * @summary Retorna os dados do usuário autenticado
 */
export const getGetUserUrl = () => {
  return `http://localhost:3333/user`
}

export const getUser = async (options?: RequestInit): Promise<GetUser200> => {
  return customFetch<GetUser200>(getGetUserUrl(), {
    ...options,
    method: 'GET',
  })
}

/**
 * Insere o plano alimentar de um usuário (cada usuário só pode ter 1 plano).
 * @summary Cria o plano alimentar do usuário
 */
export const getPostPostPlanUrl = () => {
  return `http://localhost:3333/postPlan`
}

export const postPostPlan = async (
  postPostPlanBody: PostPostPlanBody,
  options?: RequestInit,
): Promise<PostPostPlan200> => {
  return customFetch<PostPostPlan200>(getPostPostPlanUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postPostPlanBody),
  })
}

/**
 * Pega o plano alimentar de um usuário (cada usuário só pode ter 1 plano).
 * @summary Pega o plano alimentar do usuário
 */
export const getGetGetPlanUrl = () => {
  return `http://localhost:3333/getPlan`
}

export const getGetPlan = async (
  options?: RequestInit,
): Promise<GetGetPlan200> => {
  return customFetch<GetGetPlan200>(getGetGetPlanUrl(), {
    ...options,
    method: 'GET',
  })
}

/**
 * Deleta o plano alimentar de um usuário.
 * @summary Deleta o plano alimentar do usuário
 */
export const getDeleteDeletePlanUrl = () => {
  return `http://localhost:3333/deletePlan`
}

export const deleteDeletePlan = async (
  options?: RequestInit,
): Promise<DeleteDeletePlan200> => {
  return customFetch<DeleteDeletePlan200>(getDeleteDeletePlanUrl(), {
    ...options,
    method: 'DELETE',
  })
}
