/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Diet App
 * API para o Diet App
 * OpenAPI spec version: 0.0.1
 */
import { customFetch } from '../../fetchMutator'
export type PostPlanBodyActivityLevel =
  (typeof PostPlanBodyActivityLevel)[keyof typeof PostPlanBodyActivityLevel]

export const PostPlanBodyActivityLevel = {
  sedentario: 'sedentario',
  '2x_semana': '2x_semana',
  '4x_semana': '4x_semana',
} as const

export type PostPlanBodyGenre =
  (typeof PostPlanBodyGenre)[keyof typeof PostPlanBodyGenre]

export const PostPlanBodyGenre = {
  masculino: 'masculino',
  feminino: 'feminino',
  outro: 'outro',
} as const

export type PostPlanBodyGoal =
  (typeof PostPlanBodyGoal)[keyof typeof PostPlanBodyGoal]

export const PostPlanBodyGoal = {
  perda_de_peso: 'perda_de_peso',
  hipertrofia: 'hipertrofia',
  manter_massa_muscular: 'manter_massa_muscular',
} as const

export type PostPlanBody = {
  /** @minLength 2 */
  name: string
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  weight: number
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  height: number
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum
   */
  age: number
  activity_level: PostPlanBodyActivityLevel
  genre: PostPlanBodyGenre
  goal: PostPlanBodyGoal
}

export type PostPlan400 = {
  error: string
  details: unknown
}

export type PostAuthBody = {
  /** @minLength 2 */
  name?: string
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string
  /** @minLength 6 */
  password: string
}

export type PostAuth200 = {
  token: string
}

export type PostAuth400 = {
  message: string
}

export type PostAuth401 = {
  message: string
}

export type PostAuth404 = {
  message: string
}

export type PatchUserBodyActivityLevel =
  (typeof PatchUserBodyActivityLevel)[keyof typeof PatchUserBodyActivityLevel]

export const PatchUserBodyActivityLevel = {
  sedentario: 'sedentario',
  '2x_semana': '2x_semana',
  '4x_semana': '4x_semana',
} as const

export type PatchUserBodyGenre =
  (typeof PatchUserBodyGenre)[keyof typeof PatchUserBodyGenre]

export const PatchUserBodyGenre = {
  masculino: 'masculino',
  feminino: 'feminino',
  outro: 'outro',
} as const

export type PatchUserBodyGoal =
  (typeof PatchUserBodyGoal)[keyof typeof PatchUserBodyGoal]

export const PatchUserBodyGoal = {
  perda_de_peso: 'perda_de_peso',
  hipertrofia: 'hipertrofia',
  manter_massa_muscular: 'manter_massa_muscular',
} as const

export type PatchUserBody = {
  /** @minLength 2 */
  name?: string
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  weight?: number
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  height?: number
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum
   */
  age?: number
  activityLevel?: PatchUserBodyActivityLevel
  genre?: PatchUserBodyGenre
  goal?: PatchUserBodyGoal
}

export type PatchUser200 = {
  message: string
}

export type PatchUser400 = {
  message: string
}

export type PatchUser401 = {
  message: string
}

/**
 * @nullable
 */
export type GetUser200ActivityLevel =
  | (typeof GetUser200ActivityLevel)[keyof typeof GetUser200ActivityLevel]
  | null

export const GetUser200ActivityLevel = {
  sedentario: 'sedentario',
  '2x_semana': '2x_semana',
  '4x_semana': '4x_semana',
} as const

/**
 * @nullable
 */
export type GetUser200Genre =
  | (typeof GetUser200Genre)[keyof typeof GetUser200Genre]
  | null

export const GetUser200Genre = {
  masculino: 'masculino',
  feminino: 'feminino',
  outro: 'outro',
} as const

/**
 * @nullable
 */
export type GetUser200Goal =
  | (typeof GetUser200Goal)[keyof typeof GetUser200Goal]
  | null

export const GetUser200Goal = {
  perda_de_peso: 'perda_de_peso',
  hipertrofia: 'hipertrofia',
  manter_massa_muscular: 'manter_massa_muscular',
} as const

export type GetUser200 = {
  name: string
  /** @nullable */
  weight?: number | null
  /** @nullable */
  height?: number | null
  /** @nullable */
  age?: number | null
  /** @nullable */
  activity_level?: GetUser200ActivityLevel
  /** @nullable */
  genre?: GetUser200Genre
  /** @nullable */
  goal?: GetUser200Goal
}

export type GetUser401 = {
  message: string
}

export type GetUser404 = {
  message: string
}

export type GetUser500 = {
  message: string
}

export const getGetUrl = () => {
  return `http://localhost:3333/`
}

export const get = async (options?: RequestInit): Promise<void> => {
  return customFetch<void>(getGetUrl(), {
    ...options,
    method: 'GET',
  })
}

/**
 * Recebe os dados do usuário e retorna o plano alimentar em streaming (SSE).
 * @summary Gera um plano alimentar personalizado
 */
export const getPostPlanUrl = () => {
  return `http://localhost:3333/plan`
}

export const postPlan = async (
  postPlanBody: PostPlanBody,
  options?: RequestInit,
): Promise<string> => {
  return customFetch<string>(getPostPlanUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postPlanBody),
  })
}

/**
 * Se o usuário não existir, uma nova conta será criada. Se o usuário já existir, ele será autenticado.
 * @summary Cria uma nova conta ou autentica um usuário existente
 */
export const getPostAuthUrl = () => {
  return `http://localhost:3333/auth`
}

export const postAuth = async (
  postAuthBody: PostAuthBody,
  options?: RequestInit,
): Promise<PostAuth200> => {
  return customFetch<PostAuth200>(getPostAuthUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postAuthBody),
  })
}

/**
 * Permite ao usuário autenticado atualizar seus próprios dados. Todos os campos são opcionais.
 * @summary Atualiza os dados do usuário autenticado
 */
export const getPatchUserUrl = () => {
  return `http://localhost:3333/user`
}

export const patchUser = async (
  patchUserBody: PatchUserBody,
  options?: RequestInit,
): Promise<PatchUser200> => {
  return customFetch<PatchUser200>(getPatchUserUrl(), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchUserBody),
  })
}

/**
 * @summary Retorna os dados do usuário autenticado
 */
export const getGetUserUrl = () => {
  return `http://localhost:3333/user`
}

export const getUser = async (options?: RequestInit): Promise<GetUser200> => {
  return customFetch<GetUser200>(getGetUserUrl(), {
    ...options,
    method: 'GET',
  })
}
