/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Diet App
 * API para o Diet App
 * OpenAPI spec version: 0.0.1
 */
export type PostPlanBodyActivityLevel =
  (typeof PostPlanBodyActivityLevel)[keyof typeof PostPlanBodyActivityLevel]

export const PostPlanBodyActivityLevel = {
  sedentario: 'sedentario',
  '2x_semana': '2x_semana',
  '4x_semana': '4x_semana',
} as const

export type PostPlanBodyGenre =
  (typeof PostPlanBodyGenre)[keyof typeof PostPlanBodyGenre]

export const PostPlanBodyGenre = {
  masculino: 'masculino',
  feminino: 'feminino',
  outro: 'outro',
} as const

export type PostPlanBodyGoal =
  (typeof PostPlanBodyGoal)[keyof typeof PostPlanBodyGoal]

export const PostPlanBodyGoal = {
  perda_de_peso: 'perda_de_peso',
  hipertrofia: 'hipertrofia',
  manter_massa_muscular: 'manter_massa_muscular',
} as const

export type PostPlanBody = {
  /** @minLength 2 */
  name: string
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  weight: number
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  height: number
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum
   */
  age: number
  activity_level: PostPlanBodyActivityLevel
  genre: PostPlanBodyGenre
  goal: PostPlanBodyGoal
}

export type PostPlan400 = {
  error: string
  details: unknown
}

export const getGetUrl = () => {
  return `http://localhost:3333/`
}

export const get = async (options?: RequestInit): Promise<void> => {
  const res = await fetch(getGetUrl(), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: void = body ? JSON.parse(body) : {}
  return data
}

/**
 * Recebe os dados do usuário e retorna o plano alimentar em streaming (SSE).
 * @summary Gera um plano alimentar personalizado
 */
export const getPostPlanUrl = () => {
  return `http://localhost:3333/plan`
}

export const postPlan = async (
  postPlanBody: PostPlanBody,
  options?: RequestInit,
): Promise<string> => {
  const res = await fetch(getPostPlanUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postPlanBody),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: string = body ? JSON.parse(body) : {}
  return data
}
